steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "cars-downloader-pull"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/cars-downloader:latest || exit 0",
      ]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/cars-downloader:latest",
        "--file=docker/Dockerfile.cars-downloader",
        "--cache-from=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/cars-downloader:latest",
        ".",
      ]
    waitFor: ["cars-downloader-pull"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/cars-models:latest",
        "--file=docker/Dockerfile.cars-models",
        ".",
      ]
    waitFor: ["-"]

images:
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/cars-downloader:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/cars-models:latest"
