steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "api-pull"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/api:latest || exit 0",
      ]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/api:latest",
        "--file=docker/Dockerfile.api",
        "--cache-from=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/api:latest",
        ".",
      ]
    waitFor: ["api-pull"]

  - name: "gcr.io/cloud-builders/docker"
    id: "drivers-downloader-pull"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest || exit 0",
      ]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest",
        "--file=docker/Dockerfile.drivers-downloader",
        "--cache-from=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest",
        ".",
      ]
    waitFor: ["drivers-downloader-pull"]

  - name: "gcr.io/cloud-builders/docker"
    id: "leagues-parser-pull"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/leagues-parser:latest || exit 0",
      ]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/leagues-parser:latest",
        "--file=docker/Dockerfile.leagues-parser",
        "--cache-from=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/leagues-parser:latest",
        ".",
      ]
    waitFor: ["leagues-parser-pull"]

  - name: "gcr.io/cloud-builders/docker"
    id: "qualify-results-pull"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/qualify-results:latest || exit 0",
      ]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/qualify-results:latest",
        "--file=docker/Dockerfile.qualify-results",
        "--cache-from=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/qualify-results:latest",
        ".",
      ]
    waitFor: ["qualify-results-pull"]

  - name: "gcr.io/cloud-builders/docker"
    id: "season-parser-pull"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest || exit 0",
      ]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest",
        "--file=docker/Dockerfile.season-parser",
        "--cache-from=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest",
        ".",
      ]
    waitFor: ["season-parser-pull"]

  - name: "gcr.io/cloud-builders/docker"
    id: "sessions-downloader-pull"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest || exit 0",
      ]
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest",
        "--file=docker/Dockerfile.sessions-downloader",
        "--cache-from=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest",
        ".",
      ]
    waitFor: ["sessions-downloader-pull"]

images:
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/api:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/leagues-parser:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/qualify-results:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest"
