services:
  db:
    image: postgres:17
    volumes:
      - db:/var/lib/postgresql/data
      - ./utils/postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_MULTIPLE_DATABASES: events, drivers
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators pubsub start --project=some-project-id --host-port='0.0.0.0:8085'
    ports:
      - 8085:8085

volumes:
  db:
