steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker pull europe-west3-docker.pkg.dev/sharedtelemetryapp/qualify-results/qualify-results-front:latest || exit 0'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west3-docker.pkg.dev/sharedtelemetryapp/qualify-results/qualify-results-front:latest',
        '--cache-from',
        'europe-west3-docker.pkg.dev/sharedtelemetryapp/qualify-results/qualify-results-front:latest',
        '.'
      ]

images:
  ['europe-west3-docker.pkg.dev/sharedtelemetryapp/qualify-results/qualify-results-front:latest']
