steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west3-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest",
        ".",
        "--file",
        "Dockerfile",
        "--build-arg",
        "PACKAGE=events",
        "--build-arg",
        "COMMAND=run_sessions_downloader",
      ]
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west3-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest",
        ".",
        "--file",
        "Dockerfile",
        "--build-arg",
        "PACKAGE=events",
        "--build-arg",
        "COMMAND=run_season_parser",
      ]
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west3-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest",
        ".",
        "--file",
        "Dockerfile",
        "--build-arg",
        "PACKAGE=drivers",
        "--build-arg",
        "COMMAND=run_drivers_downloader",
      ]
    waitFor: ["-"]

images:
  - "europe-west3-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest"
  - "europe-west3-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest"
  - "europe-west3-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest"
