steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest",
        "--file=events/Dockerfile",
        "--build-arg",
        "COMMAND=run_sessions_downloader",
        ".",
      ]
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest",
        "--file=events/Dockerfile",
        "--build-arg",
        "COMMAND=run_season_parser",
        ".",
      ]
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/leagues-parser:latest",
        "--file=events/Dockerfile",
        "--build-arg",
        "COMMAND=run_leagues_parser",
        ".",
      ]
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--tag=europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest",
        "--file=drivers/Dockerfile",
        "--build-arg",
        "COMMAND=run_drivers_downloader",
        ".",
      ]
    waitFor: ["-"]

images:
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/sessions-downloader:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/season-parser:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/drivers-downloader:latest"
  - "europe-west1-docker.pkg.dev/sharedtelemetryapp/sessions-downloader/leagues-parser:latest"
